### ISSUE TITLE
sf or sp ?

### ISSUE THREAD

**Issue by Jean-Romain** [Jean-Romain/lidR-v2.0#3]
`lidR` will be fully compatible with "spatial" data:

- `grid_*` will return `RasterLayers` or `RasterStacks`
- `tree_detection_*`, `tree_metrics` will `tree_metrics` return `SpatialPointsDataFrame`
- `tree_hull` returns `SpatialPolygonsDataFrame`
- `lasclip` will support `Polygon`, `Polygons `, `SpatialPolygons`,  `SpatialPolygonsDataFrame`, `RasterLayers`, `Extent`, `SimpleFeature`
- `proj4string` will be supported in each function.
- function `lasreproject` is in the plan
- and so on

I'm wondering if `lidR` should natively return `sp`or `sf` objects. `sp`is well known by the community. Each time somebody exchange via github or mail with me the object he manipulates are from `sp`. I don't have other arguments in favor or not of `sp` vs `sf`.

**Comment by GreKro** [comment]
the best solution will be to support these two "formats" if it posible
sf is relatively new library but is developed all the time, I think it is the main reason of using 'good old stable' sp objects by the R community, huge advatange of sf library is speed of reading data to R (about 7 x faster in compare to rgdal (sp)) I suppose this will also speed up work with geometries in lidR (?)

**Comment by Jean-Romain** [comment]
Thank you for your contribution.

Support of the two formats is a solution that requires a lot of work. Every function, every input must be tested twice more time. Once if the input/output is a `sp` once if it is `sf`. And each function must have several different versions.

For example the new functions `lasclip` support WTK string, `sp::Polygon`, `sp::Polygons`, `sp::SpatialPolygons`, `sp::SpatialPolygonsDataFrame`, `raster::Extent` and `sf::SimpleFeature` both with `LAS`and `LAScatalog` (how `LAS` object and `LAScatalog` objects are managed is very different). To be memory optimized, I should have almost one version of `lasclip` per input. In practice there is a single one and whatever the input it is casted into an `sf` object and internally I almost only deal with WKT strings that unify all the options. Otherwise it is not manageable.

Thus, dealing with several possible "mode" seems unmanageable to me. Or in a very naive way. For the outputs, for example, something like that:

```r
if (lidR_mode == "sf")
  return(sf::st_as_sf(output))
else
  return(output)
```

That can also be done by the user!

>  I suppose this will also speed up work with geometries in lidR (?)

lidR mostly deal with point clouds. The output format is usually a negligible time compared to the computation itself. I mean, for example in a tree segmentation the segmentation requires a huge computation time compared to the formatting of the output. `sp` of `sf` that will not speed-up anything in this case. 

Please notice I'm not rejecting your ideas. This repos is for discussions. We are discussing :wink: . I'm listening to the arguments and nobody is right or wrong. At the end maybe I will make two "modes" but for now is seems not really manageable.

**Comment by GreKro** [comment]
Of course I know We are discussing :) This solution would be perfect for users but I totaly understand that is pretty hard work for you, time-consuming etc. Returning to the topic it looks like it is best to use sp objects as native lidR geom outputs at the moment (your expirience with other users)

**Comment by Jean-Romain** [comment]
@jfbourdon ok but let me ask the question in another way: let assume I apply the function `tree_detection` over a `LAScatalog` of 400 km².  It returns 10-12 millions of (X,Y,Z) coordinates in  400 `SpatialPointsDataFrame` or `SimpleFeature` that will be staked into a single one before to be returned to the user. Which one is the most suitable.

**Comment by edzer** [comment]
For storing massive point sets, sp is definitely more efficient than sf:
```r
> library(sp)
> pts = SpatialPoints(matrix(0.1, 100000, 2))
> object.size(pts)
1602896 bytes
> object.size(sf::st_as_sfc(pts))
43202320 bytes
```
`sf` stores geometries in a list column, each point is a list entry with a length 2 numeric vector; in `sp` the whole set is stored in an n x 2 matrix. 

This is a consequence of putting everything in a single, coherent framework of simple features and list columns with geometries (tidyverse).

**Comment by Jean-Romain** [comment]
Thank you @edzer. I think that close the discussion and I'm not surprised by the answer. I will rely on `sp` mainly. For non massive data the user will be able to transform the outputs into `sf`  when preferred.
